// Code generated by MockGen. DO NOT EDIT.
// Source: internal/services/in_app_store/service.go
//
// Generated by this command:
//
//	mockgen -source=internal/services/in_app_store/service.go -destination=mocks/mock_in_app_store_service.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	dto "github.com/darkwingdck/adora-coding-assessment/internal/dto"
	gomock "go.uber.org/mock/gomock"
)

// MockService is a mock of Service interface.
type MockService struct {
	ctrl     *gomock.Controller
	recorder *MockServiceMockRecorder
	isgomock struct{}
}

// MockServiceMockRecorder is the mock recorder for MockService.
type MockServiceMockRecorder struct {
	mock *MockService
}

// NewMockService creates a new mock instance.
func NewMockService(ctrl *gomock.Controller) *MockService {
	mock := &MockService{ctrl: ctrl}
	mock.recorder = &MockServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockService) EXPECT() *MockServiceMockRecorder {
	return m.recorder
}

// UpdateUserEntitlement mocks base method.
func (m *MockService) UpdateUserEntitlement(ctx context.Context, cmd dto.UpdateUserEntitlementCmd) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateUserEntitlement", ctx, cmd)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateUserEntitlement indicates an expected call of UpdateUserEntitlement.
func (mr *MockServiceMockRecorder) UpdateUserEntitlement(ctx, cmd any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateUserEntitlement", reflect.TypeOf((*MockService)(nil).UpdateUserEntitlement), ctx, cmd)
}
