// Code generated by MockGen. DO NOT EDIT.
// Source: store/service.go
//
// Generated by this command:
//
//	mockgen -source=store/service.go -destination=mocks/mock_store.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	dto "github.com/darkwingdck/adora-coding-assessment/internal/dto"
	store "github.com/darkwingdck/adora-coding-assessment/store"
	pgx "github.com/jackc/pgx/v5"
	pgconn "github.com/jackc/pgx/v5/pgconn"
	gomock "go.uber.org/mock/gomock"
)

// Mockquerier is a mock of querier interface.
type Mockquerier struct {
	ctrl     *gomock.Controller
	recorder *MockquerierMockRecorder
	isgomock struct{}
}

// MockquerierMockRecorder is the mock recorder for Mockquerier.
type MockquerierMockRecorder struct {
	mock *Mockquerier
}

// NewMockquerier creates a new mock instance.
func NewMockquerier(ctrl *gomock.Controller) *Mockquerier {
	mock := &Mockquerier{ctrl: ctrl}
	mock.recorder = &MockquerierMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *Mockquerier) EXPECT() *MockquerierMockRecorder {
	return m.recorder
}

// Exec mocks base method.
func (m *Mockquerier) Exec(ctx context.Context, sql string, arguments ...any) (pgconn.CommandTag, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, sql}
	for _, a := range arguments {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Exec", varargs...)
	ret0, _ := ret[0].(pgconn.CommandTag)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Exec indicates an expected call of Exec.
func (mr *MockquerierMockRecorder) Exec(ctx, sql any, arguments ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, sql}, arguments...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Exec", reflect.TypeOf((*Mockquerier)(nil).Exec), varargs...)
}

// Query mocks base method.
func (m *Mockquerier) Query(ctx context.Context, sql string, args ...any) (pgx.Rows, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, sql}
	for _, a := range args {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Query", varargs...)
	ret0, _ := ret[0].(pgx.Rows)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Query indicates an expected call of Query.
func (mr *MockquerierMockRecorder) Query(ctx, sql any, args ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, sql}, args...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Query", reflect.TypeOf((*Mockquerier)(nil).Query), varargs...)
}

// QueryRow mocks base method.
func (m *Mockquerier) QueryRow(ctx context.Context, sql string, args ...any) pgx.Row {
	m.ctrl.T.Helper()
	varargs := []any{ctx, sql}
	for _, a := range args {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "QueryRow", varargs...)
	ret0, _ := ret[0].(pgx.Row)
	return ret0
}

// QueryRow indicates an expected call of QueryRow.
func (mr *MockquerierMockRecorder) QueryRow(ctx, sql any, args ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, sql}, args...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "QueryRow", reflect.TypeOf((*Mockquerier)(nil).QueryRow), varargs...)
}

// MockStore is a mock of Store interface.
type MockStore struct {
	ctrl     *gomock.Controller
	recorder *MockStoreMockRecorder
	isgomock struct{}
}

// MockStoreMockRecorder is the mock recorder for MockStore.
type MockStoreMockRecorder struct {
	mock *MockStore
}

// NewMockStore creates a new mock instance.
func NewMockStore(ctrl *gomock.Controller) *MockStore {
	mock := &MockStore{ctrl: ctrl}
	mock.recorder = &MockStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStore) EXPECT() *MockStoreMockRecorder {
	return m.recorder
}

// CreateNotification mocks base method.
func (m *MockStore) CreateNotification(ctx context.Context, cmd dto.CreateNotificationCmd) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateNotification", ctx, cmd)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateNotification indicates an expected call of CreateNotification.
func (mr *MockStoreMockRecorder) CreateNotification(ctx, cmd any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateNotification", reflect.TypeOf((*MockStore)(nil).CreateNotification), ctx, cmd)
}

// CreateStoreEvent mocks base method.
func (m *MockStore) CreateStoreEvent(ctx context.Context, cmd dto.CreateStoreEventCmd) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateStoreEvent", ctx, cmd)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateStoreEvent indicates an expected call of CreateStoreEvent.
func (mr *MockStoreMockRecorder) CreateStoreEvent(ctx, cmd any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateStoreEvent", reflect.TypeOf((*MockStore)(nil).CreateStoreEvent), ctx, cmd)
}

// GetCarrierEntitlements mocks base method.
func (m *MockStore) GetCarrierEntitlements(ctx context.Context) ([]*store.Entitlement, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCarrierEntitlements", ctx)
	ret0, _ := ret[0].([]*store.Entitlement)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCarrierEntitlements indicates an expected call of GetCarrierEntitlements.
func (mr *MockStoreMockRecorder) GetCarrierEntitlements(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCarrierEntitlements", reflect.TypeOf((*MockStore)(nil).GetCarrierEntitlements), ctx)
}

// GetEntitlementByUserID mocks base method.
func (m *MockStore) GetEntitlementByUserID(ctx context.Context, cmd dto.GetEntitlementByUserIDCmd) (*store.Entitlement, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetEntitlementByUserID", ctx, cmd)
	ret0, _ := ret[0].(*store.Entitlement)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetEntitlementByUserID indicates an expected call of GetEntitlementByUserID.
func (mr *MockStoreMockRecorder) GetEntitlementByUserID(ctx, cmd any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetEntitlementByUserID", reflect.TypeOf((*MockStore)(nil).GetEntitlementByUserID), ctx, cmd)
}

// GetPendingNotifications mocks base method.
func (m *MockStore) GetPendingNotifications(ctx context.Context) ([]*store.Notification, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPendingNotifications", ctx)
	ret0, _ := ret[0].([]*store.Notification)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPendingNotifications indicates an expected call of GetPendingNotifications.
func (mr *MockStoreMockRecorder) GetPendingNotifications(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPendingNotifications", reflect.TypeOf((*MockStore)(nil).GetPendingNotifications), ctx)
}

// MarkNotificationSent mocks base method.
func (m *MockStore) MarkNotificationSent(ctx context.Context, cmd dto.MarkNotificationSentCmd) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MarkNotificationSent", ctx, cmd)
	ret0, _ := ret[0].(error)
	return ret0
}

// MarkNotificationSent indicates an expected call of MarkNotificationSent.
func (mr *MockStoreMockRecorder) MarkNotificationSent(ctx, cmd any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MarkNotificationSent", reflect.TypeOf((*MockStore)(nil).MarkNotificationSent), ctx, cmd)
}

// RevokeMarketplaceEntitlements mocks base method.
func (m *MockStore) RevokeMarketplaceEntitlements(ctx context.Context, cmd dto.RevokeMarketplaceEntitlementsCmd) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RevokeMarketplaceEntitlements", ctx, cmd)
	ret0, _ := ret[0].(error)
	return ret0
}

// RevokeMarketplaceEntitlements indicates an expected call of RevokeMarketplaceEntitlements.
func (mr *MockStoreMockRecorder) RevokeMarketplaceEntitlements(ctx, cmd any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RevokeMarketplaceEntitlements", reflect.TypeOf((*MockStore)(nil).RevokeMarketplaceEntitlements), ctx, cmd)
}

// UpsertEntitlement mocks base method.
func (m *MockStore) UpsertEntitlement(ctx context.Context, cmd dto.UpsertEntitlementCmd) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpsertEntitlement", ctx, cmd)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpsertEntitlement indicates an expected call of UpsertEntitlement.
func (mr *MockStoreMockRecorder) UpsertEntitlement(ctx, cmd any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpsertEntitlement", reflect.TypeOf((*MockStore)(nil).UpsertEntitlement), ctx, cmd)
}

// WithTransaction mocks base method.
func (m *MockStore) WithTransaction(ctx context.Context, fn func(store.Store) error) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WithTransaction", ctx, fn)
	ret0, _ := ret[0].(error)
	return ret0
}

// WithTransaction indicates an expected call of WithTransaction.
func (mr *MockStoreMockRecorder) WithTransaction(ctx, fn any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WithTransaction", reflect.TypeOf((*MockStore)(nil).WithTransaction), ctx, fn)
}
