// Code generated by MockGen. DO NOT EDIT.
// Source: internal/services/in_app_store/service.go
//
// Generated by this command:
//
//	mockgen -source=internal/services/in_app_store/service.go -destination=mocks/mock_in_app_store_service.go -package=mocks -mock_names=Service=MockInAppStoreService
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	dto "github.com/darkwingdck/adora-coding-assessment/internal/dto"
	gomock "go.uber.org/mock/gomock"
)

// MockInAppStoreService is a mock of Service interface.
type MockInAppStoreService struct {
	ctrl     *gomock.Controller
	recorder *MockInAppStoreServiceMockRecorder
	isgomock struct{}
}

// MockInAppStoreServiceMockRecorder is the mock recorder for MockInAppStoreService.
type MockInAppStoreServiceMockRecorder struct {
	mock *MockInAppStoreService
}

// NewMockInAppStoreService creates a new mock instance.
func NewMockInAppStoreService(ctrl *gomock.Controller) *MockInAppStoreService {
	mock := &MockInAppStoreService{ctrl: ctrl}
	mock.recorder = &MockInAppStoreServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockInAppStoreService) EXPECT() *MockInAppStoreServiceMockRecorder {
	return m.recorder
}

// UpdateUserEntitlement mocks base method.
func (m *MockInAppStoreService) UpdateUserEntitlement(ctx context.Context, cmd dto.UpdateUserEntitlementCmd) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateUserEntitlement", ctx, cmd)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateUserEntitlement indicates an expected call of UpdateUserEntitlement.
func (mr *MockInAppStoreServiceMockRecorder) UpdateUserEntitlement(ctx, cmd any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateUserEntitlement", reflect.TypeOf((*MockInAppStoreService)(nil).UpdateUserEntitlement), ctx, cmd)
}
