// Code generated by MockGen. DO NOT EDIT.
// Source: internal/services/mobile_carrier/service.go
//
// Generated by this command:
//
//	mockgen -source=internal/services/mobile_carrier/service.go -destination=mocks/mock_mobile_carrier_service.go -package=mocks -mock_names=Service=MockMobileCarrierService
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	dto "github.com/darkwingdck/adora-coding-assessment/internal/dto"
	gomock "go.uber.org/mock/gomock"
)

// MockMobileCarrierService is a mock of Service interface.
type MockMobileCarrierService struct {
	ctrl     *gomock.Controller
	recorder *MockMobileCarrierServiceMockRecorder
	isgomock struct{}
}

// MockMobileCarrierServiceMockRecorder is the mock recorder for MockMobileCarrierService.
type MockMobileCarrierServiceMockRecorder struct {
	mock *MockMobileCarrierService
}

// NewMockMobileCarrierService creates a new mock instance.
func NewMockMobileCarrierService(ctrl *gomock.Controller) *MockMobileCarrierService {
	mock := &MockMobileCarrierService{ctrl: ctrl}
	mock.recorder = &MockMobileCarrierServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMobileCarrierService) EXPECT() *MockMobileCarrierServiceMockRecorder {
	return m.recorder
}

// GetMobileCarrierUserStatus mocks base method.
func (m *MockMobileCarrierService) GetMobileCarrierUserStatus(ctx context.Context, cmd dto.GetMobileCarrierUserStatusCmd) (*dto.GetMobileCarrierUserStatusResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMobileCarrierUserStatus", ctx, cmd)
	ret0, _ := ret[0].(*dto.GetMobileCarrierUserStatusResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetMobileCarrierUserStatus indicates an expected call of GetMobileCarrierUserStatus.
func (mr *MockMobileCarrierServiceMockRecorder) GetMobileCarrierUserStatus(ctx, cmd any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMobileCarrierUserStatus", reflect.TypeOf((*MockMobileCarrierService)(nil).GetMobileCarrierUserStatus), ctx, cmd)
}
